steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "GCP_Terraform" ]; then
        terraform init
      else
        for dir in GCP_Terraform/
        do 
          terraform init || exit 1
        done
      fi 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "GCP_Terraform" ]; then
        terraform plan -lock=false
      else
        for dir in GCP_Terraform/
        do 
          terraform plan -lock=false || exit 1
        done
      fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "GCP_Terraform" ]; then    
        terraform apply -lock=false -auto-approve
      else
      fi
# [END tf-apply]


# [START execute-sql]
- id: Execute SQL file
  name: postgres:14
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      psql -U ${DB_USERNAME} -W -d ${DB_NAME} -f ${SQL_FILE_PATH}
# [END execute-sql]

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
