steps:
- id: 'Fetching Branch Name'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "Terraform/environments/$BRANCH_NAME/" ]; then
        cd Terraform/environments/$BRANCH_NAME/bucket/
        terraform init
      else
        for dir in Terraform/environments/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "Terraform/environments/$BRANCH_NAME/" ]; then
        cd Terraform/environments/$BRANCH_NAME/bucket/
        terraform plan -lock=false
      else
        for dir in Terraform/environments/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan -lock=false || exit 1
          cd ../../
        done
      fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "Terraform/environments/$BRANCH_NAME/" ]; then
        cd Terraform/environments/$BRANCH_NAME/bucket/     
        terraform apply -lock=false -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "*******************************************************************************"
      fi
# [END tf-apply]
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
